### ISSUE TITLE
问题请教

### ISSUE THREAD

**Issue by NTmemoir** [BestDingSheng/node-test-demo#1]
请问你的服务器和域名是在哪里买的啊？新手求教

**Comment by BestDingSheng** [comment]
我在阿里云买的

**Comment by NTmemoir** [comment]
是买的云虚拟主机吗？还是什么？

**Comment by BestDingSheng** [comment]
![image](https://user-images.githubusercontent.com/13111768/33354635-ca439fa0-d4ee-11e7-91bc-4d311bd959f6.png)
这个

**Comment by NTmemoir** [comment]
ok,谢谢了
